name: Mirror Repo
on:
  schedule:
    - cron:  '*/15 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Mirror
      run: |
        git clone --mirror https://git.earnestma.xyz/earnestma/ledgerscoop.git
        cd ledgerscoop.git
        git remote add github "https://eeeee-bot:$TOKEN@github.com/earnestma/ledgerscoop.git"
        git push --mirror github
      env:
        TOKEN: ${{ secrets.TOKEN }}
